%%%%%%%%%%%%%%%%%%%%%%%%%%%
% You must fill the following information correctly.
%
% Final Exam Number: …
% Problem number: …
% Student Name:  …
% Student ID: …
% Email address: …
% Department:
% Date: …
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

close all; clear; clc;		% close all windows
                            % clear variables, and clear screen

disp('Final Exam Problem 2.?') 	% show Midterm Problem ?.?

disp('Student Name; Student ID');
